INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (1, '12345678', null, 'uploads/products/2/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (2, '12345678', null, 'uploads/products/3/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (3, '12345678', null, 'uploads/products/4/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (4, '12345678', null, 'uploads/products/5/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (5, '12345678', null, 'uploads/products/6/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (6, '12345678', null, 'uploads/products/7/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (7, '12345678', null, 'uploads/products/8/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (8, '12345678', null, 'uploads/products/9/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (9, '12345678', null, 'uploads/products/10/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (10, '12345678', null, 'uploads/products/11/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (11, '12345678', null, 'uploads/products/12/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (12, '12345678', null, 'uploads/products/13/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (13, '12345678', null, 'uploads/products/14/u92 (copy).png', null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (14, '1116', 'chipes', null, null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (15, '51584', 'pepsi', null, null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (16, '1155', 'fruts', null, null, null);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (17, '123456781', null, 'uploads/products/18/Screenshot from 2019-03-30 09-55-47.png', null, 123456781);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (18, '123456781', null, 'uploads/products/19/Screenshot from 2019-03-30 09-55-47.png', null, 123456781);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (19, '123456781', null, null, null, 123456781);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (20, '123456781', null, null, null, 123456781);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (21, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (22, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (23, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (24, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (25, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (26, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (27, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (28, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (29, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (30, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (31, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (32, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (33, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (34, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (35, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (36, null, '11', null, null, 1);
INSERT INTO vooom.product (id, barcode, name, image, status, price) VALUES (37, null, '11', null, null, 1);